config/routes.rb
Rails.application.routes.draw do
  root to: 'stacks#index'
  get 'stats/index'
  get '/imprint', to: 'application#imprint'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users, only: [:show, :edit, :update, :destroy]
  get '/statistics', to: 'stats#index'

  resources :stacks, except: [:edit, :update] do
    resources :flashcards
  end

  get '/flashcards/:id/next', to: 'flashcards#next', as: :next_card
end

app/models/flashcard.rb
class Flashcard < ApplicationRecord
  belongs_to :stack
  delegate :title, to: :stack, prefix: true
  validates :question, presence: true
  has_many :completed_flashcards, dependent: :destroy

  def next
    Flashcard.where(['id > ? and stack_id = ?', id, stack_id]).first
  end

  def type_symbol
    type_symbol_map = {
      'OpenAnswer' => :open_answer,
      'MultipleChoice' => :multiple_choice,
      'SingleChoice' => :single_choice,
      'TrueFalse' => :true_false
    }

    type_symbol_map[type]
  end
end

app/controllers/flashcards_controller.rb
class FlashcardsController < ApplicationController
  def index
    @stack = Stack.find(params[:stack_id])
    @flashcards = @stack.flashcards
  end

  def new
    @stack = Stack.find(params[:stack_id])
  end

  def create
    @stack = Stack.find(params[:stack_id])
    @flashcard = @stack.flashcards.new(new_flashcard_params)

    if @flashcard.save
      render partial: 'flashcard_created', locals: { stack: @stack }
    else
      render partial: 'flashcard_created', locals: { stack: @stack }, alert: 'Flashcard konnte nicht erstellt werden.'
    end
  end

  def edit
    @flashcard = Flashcard.find(params[:id])
  end

  def update
    @flashcard = Flashcard.find(params[:id])

    if @flashcard.update(new_flashcard_params)
      render plain: stack_path(@flashcard.stack)
    else
      render plain: edit_stack_flashcard_path(@flashcard.stack, @flashcard), alert: 'Flashcard konnte nicht gespeichert werden'
    end
  end

  def destroy
    @flashcard = Flashcard.find(params[:id])
    @flashcard.destroy
    redirect_to stack_path(@flashcard.stack)
  end

  def show
    @flashcard = Flashcard.find(params[:id])
    if @flashcard == @flashcard.stack.flashcards.first
      session[:open_answer] = 0
      session[:multiple_choice] = 0
      session[:single_choice] = 0
      session[:true_false] = 0
    end
  end

  def next
    @flashcard = Flashcard.find(params[:id])
    current_user.completed_flashcards.create(flashcard_id: @flashcard.id)
    session[@flashcard.type_symbol] += 1 if params[:correct] == 'true'
    next_card = @flashcard.next

    if next_card
      redirect_to stack_flashcard_path(@flashcard.stack, next_card)
    else
      endscreen_data
      render 'endscreen'
    end
  end

  def flashcard_params
    params.permit :id, :stack_id, :correct
  end

  helper_method :flashcard_params

  private
    def endscreen_data
      stack = @flashcard.stack
      counts = stack.flashcards.group(:type).count
      counts.transform_values!(&:to_f)

      open_answer = 0
      unless counts['OpenAnswer'].nil? || counts['OpenAnswer'] == 0
        open_answer = session[:open_answer] / counts['OpenAnswer'] * 100
      end

      multiple_choice = 0
      unless counts['MultipleChoice'].nil? || counts['MultipleChoice'] == 0
        multiple_choice = session[:multiple_choice] / counts['MultipleChoice'] * 100
      end

      single_choice = 0
      unless counts['SingleChoice'].nil? || counts['SingleChoice'] == 0
        single_choice = session[:single_choice] / counts['SingleChoice'] * 100
      end

      true_false = 0
      unless counts['TrueFalse'].nil? || counts['TrueFalse'] == 0
        true_false = session[:true_false] / counts['TrueFalse'] * 100
      end

      @percentages = {
        open_answer: open_answer,
        multiple_choice: multiple_choice,
        single_choice: single_choice,
        true_false: true_false,
      }
    end

    def new_flashcard_params
      params.require(:flashcard).permit(
        :question,
        :notes,
        :type,
        :answer,
        :option1,
        :option2,
        :option3,
        :option4,
        :option1_correct,
        :option2_correct,
        :option3_correct,
        :option4_correct,
        :correct_option,
        :correct,
        :stack_id
      )
    end
end

app/views/flashcards/_card_back.html.erb
<div class='card-back card indigo answer'>
  <div>
    <p class="ellipsis"><%= flashcard.question %></p>

    <% case flashcard.type %>
      <% when 'MultipleChoice' %>
        <ul>
          <li class='bold <%= 'correct' if flashcard.option1_correct %>'><%= flashcard.option1 %></li>
          <li class='bold <%= 'correct' if flashcard.option2_correct %>'><%= flashcard.option2 %></li>
          <li class='bold <%= 'correct' if flashcard.option3_correct %>'><%= flashcard.option3 %></li>
          <li class='bold <%= 'correct' if flashcard.option4_correct %>'><%= flashcard.option4 %></li>
        </ul>
      <% when 'SingleChoice' %>
        <ul>
          <li class='bold <%= 'correct' if flashcard.correct_option == 1 %>'><%= flashcard.option1 %></li>
          <li class='bold <%= 'correct' if flashcard.correct_option == 2 %>'><%= flashcard.option2 %></li>
          <li class='bold <%= 'correct' if flashcard.correct_option == 3 %>'><%= flashcard.option3 %></li>
          <li class='bold <%= 'correct' if flashcard.correct_option == 4 %>'><%= flashcard.option4 %></li>
        </ul>
      <% when 'TrueFalse' %>
        <h3>Die Aussage ist <%= flashcard.correct ? 'wahr' : 'falsch' %>.</h3>
      <% else %>
        <h3 class="ellipsis"><%= flashcard.answer %></h3>
    <% end %>
  </div>

  <div class='action-buttons'>
    <button class='button circle white notes' id='notes-button' onclick='showNotes()'>
      <%= image_pack_tag 'bulb.png', alt: 'Notizen' %>
    </button>

    <%= link_to next_card_path(flashcard_params.merge(correct: :true)), id: 'open-correct', class: 'invisible button circle green' do %>
      <%= render partial: 'shared/icons/check' %>
    <% end %>

    <%= link_to next_card_path(flashcard_params.merge(correct: :false)), id: 'open-incorrect', class: 'invisible button circle red' do %>
      <%= render partial: 'shared/icons/cross' %>
    <% end %>

    <%= link_to next_card_path(flashcard_params.merge(correct: :true)), id: 'next-correct', class: 'invisible button circle white' do %>
      <%= render partial: 'shared/icons/next' %>
    <% end %>

    <%= link_to next_card_path(flashcard_params.merge(correct: :false)), id: 'next-incorrect', class: 'invisible button circle white' do %>
      <%= render partial: 'shared/icons/next' %>
    <% end %>
  </div>
</div>

app/views/flashcards/_card_front.html.erb
<div class='card-front card indigo question' data-type='<%= flashcard.type %>'>
  <div>
    <div class='type-wrapper'>
      <div class='left'></div>
      <p class='question-type type'><%= flashcard.type_string %></p>
      <div class='right'></div>
    </div>
    <h3 class="ellipsis"><%= flashcard.question %></h3>

    <% case flashcard.type %>
      <% when 'MultipleChoice' %>
        <div class='answers multiple-choice' id='MultipleChoice'>
          <div class='horizontal-input'>
            <input type='checkbox' id='mc-option1-correct' name='option1' value='1'>
            <label class='bold' id='mc-option1' for='mc-option1-correct' data-is-correct='<%= flashcard.option1_correct %>'><%= flashcard.option1 %></label>
          </div>
          <div class='horizontal-input'>
            <input type='checkbox' id='mc-option2-correct' name='option2' value='2'>
            <label class='bold' id='mc-option2' for='mc-option2-correct' data-is-correct='<%= flashcard.option2_correct %>'><%= flashcard.option2 %></label>
          </div>
          <div class='horizontal-input'>
            <input type='checkbox' id='mc-option3-correct' name='option3' value='3'>
            <label class='bold' id='mc-option3' for='mc-option3-correct' data-is-correct='<%= flashcard.option3_correct %>'><%= flashcard.option3 %></label>
          </div>
          <div class='horizontal-input'>
            <input type='checkbox' id='mc-option4-correct' name='option4' value='4'>
            <label class='bold' id='mc-option4' for='mc-option4-correct' data-is-correct='<%= flashcard.option4_correct %>'><%= flashcard.option4 %></label>
          </div>
        </div>
      <% when 'SingleChoice' %>
        <div class='answers single-choice' id='SingleChoice' data-correct-option='<%= flashcard.correct_option %>'>
          <div class='horizontal-input'>
            <input type='radio' id='sc-option1' name='sc-correct' value='1' checked>
            <label class='bold' id='sc-option1' for='sc-option1'><%= flashcard.option1 %></label>
          </div>
          <div class='horizontal-input'>
            <input type='radio' id='sc-option2' name='sc-correct' value='2'>
            <label class='bold' id='sc-option2' for='sc-option2'><%= flashcard.option2 %></label>
          </div>
          <div class='horizontal-input'>
            <input type='radio' id='sc-option3' name='sc-correct' value='3'>
            <label class='bold' id='sc-option3' for='sc-option3'><%= flashcard.option3 %></label>
          </div>
          <div class='horizontal-input'>
            <input type='radio' id='sc-option4' name='sc-correct' value='4'>
            <label class='bold' id='sc-option4' for='sc-option4'><%= flashcard.option4 %></label>
          </div>
        </div>
      <% when 'TrueFalse' %>
        <div class='answers true-false' id='TrueFalse' data-correct='<%= flashcard.correct %>'>
          <div class='horizontal-input'>
            <input type='radio' id='true' name='true-false' value='true' checked>
            <label class='bold' for='true'>Wahr</label>
          </div>
          <div class='horizontal-input'>
            <input type='radio' id='false' name='true-false' value='false'>
            <label class='bold' for='false'>Falsch</label>
          </div>
        </div>
      <% else %>
    <% end %>
  </div>

  <div class='action-buttons'>
    <button class='button circle white' onclick='checkAnswers()'>
      <%= render partial: 'shared/icons/turn' %>
    </button>
  </div>
</div>

<div class='card-front card indigo invisible' id='notes-card'>
  <div>
    <h3>Notizen</h3>
    <p><%= flashcard.notes %></p>
  </div>
  <button class='button circle white' onclick='flipCard()'>
    <%= render partial: 'shared/icons/back' %>
  </button>
</div>

app/views/flashcards/_flashcard_created.html.erb
<div class='card-created-buttons'>
  <%= link_to 'Weitere Frage', new_stack_flashcard_path(stack), class: 'button primary orange' %>
  <%= link_to 'Fertig', stack_path(stack), class: 'button secondary orange' %>
</div>

app/views/flashcards/edit.html.erb
<%= render partial: 'shared/header', locals: { title: @flashcard.stack_title, color: 'orange' } %>
<%= render 'shared/errors' %>
<div class='card-wrapper'>
  <div class='card-inner'>
    <div class='card card-front orange question' id='front'>
      <div>
        <div class='type-wrapper'>
          <div class='left'></div>
          <p class='type' data-type='<%= @flashcard.type %>'><%= @flashcard.type_string %></p>
          <div class='right'></div>
        </div>
        <h3 id='question' contenteditable='true' data-stack-id='<%= @flashcard.stack.id %>' data-flashcard-id='<%= @flashcard.id %>'><%= @flashcard.question %></h3>
      </div>
      <div class='action-buttons'>
        <button class='button circle white' onclick="showAnswerSide()">
          <%= render partial: 'shared/icons/turn' %>
        </button>
      </div>
    </div>

    <div class='card card-front orange invisible' id='notes'>
      <div>
        <h3>Notizen</h3>
        <p id='notes-text' contenteditable='true'><%= @flashcard.notes %></p>
      </div>
      <button class='button circle white' onclick="flipCard()">
        <%= render partial: 'shared/icons/back' %>
      </button>
    </div>

    <div class='card card-back orange answer' id='back'>
      <div>
        <p class='question'>Frage</p>
        <% case @flashcard.type %>
          <% when 'OpenAnswer' %>
            <div class='answers open-answer' id='OpenAnswer'><h3 id='answer' contenteditable='true'><%= @flashcard.answer %></h3></div>

          <% when 'MultipleChoice' %>
            <div class='answers multiple-choice' id='MultipleChoice'>
              <div class='horizontal-input'>
                <input type='checkbox' id='mc-option1-correct' name='option1' value='1' <%= 'checked' if @flashcard.option1_correct %>>
                <label contenteditable='true' id='mc-option1' class='bold'><%= @flashcard.option1 %></label>
              </div>
              <div class='horizontal-input'>
                <input type='checkbox' id='mc-option2-correct' name='option2' value='2' <%= 'checked' if @flashcard.option2_correct %>>
                <label contenteditable='true' id='mc-option2' class='bold'><%= @flashcard.option2 %></label>
              </div>
              <div class='horizontal-input'>
                <input type='checkbox' id='mc-option3-correct' name='option3' value='3' <%= 'checked' if @flashcard.option3_correct %>>
                <label contenteditable='true' id='mc-option3' class='bold'><%= @flashcard.option3 %></label>
              </div>
              <div class='horizontal-input'>
                <input type='checkbox' id='mc-option4-correct' name='option4' value='4' <%= 'checked' if @flashcard.option4_correct %>>
                <label contenteditable='true' id='mc-option4' class='bold'><%= @flashcard.option4 %></label>
              </div>
              <div class='horizontal-input select-hint'>
                <%= render 'shared/icons/corner' %>
                <p>Richtige auswählen</p>
              </div>
            </div>

          <% when 'SingleChoice' %>
            <div class='answers single-choice' id='SingleChoice'>
              <div class='horizontal-input'>
                <input type='radio' id='option1' name='sc-correct' value='1' <%= 'checked' if @flashcard.correct_option == 1 %>>
                <label contenteditable='true' id='sc-option1' class='bold'><%= @flashcard.option4 %></label>
              </div>
              <div class='horizontal-input'>
                <input type='radio' id='option2' name='sc-correct' value='2' <%= 'checked' if @flashcard.correct_option == 2 %>>
                <label contenteditable='true' id='sc-option2' class='bold'><%= @flashcard.option2 %></label>
              </div>
              <div class='horizontal-input'>
                <input type='radio' id='option3' name='sc-correct' value='3' <%= 'checked' if @flashcard.correct_option == 3 %>>
                <label contenteditable='true' id='sc-option3' class='bold'><%= @flashcard.option3 %></label>
              </div>
              <div class='horizontal-input'>
                <input type='radio' id='option4' name='sc-correct' value='4' <%= 'checked' if @flashcard.correct_option == 4 %>>
                <label contenteditable='true' id='sc-option4' class='bold'><%= @flashcard.option4 %></label>
              </div>
              <div class='horizontal-input select-hint'>
                <%= render 'shared/icons/corner' %>
                <p>Richtiges auswählen</p>
              </div>
            </div>

          <% when 'TrueFalse' %>
            <div class='answers true-false' id='TrueFalse'>
              <div class='horizontal-input'>
                <input type='radio' id='true' name='true-false' value='true' <%= 'checked' if @flashcard.correct == true %>>
                <label for='true' class='bold'>Wahr</label>
              </div>
              <div class='horizontal-input'>
                <input type='radio' id='false' name='true-false' value='false' <%= 'checked' if @flashcard.correct == false %>>
                <label for='false' class='bold'>Falsch</label>
              </div>
            </div>
          <% else %>
        <% end %>
      </div>
      <div class='action-buttons'>
        <button class='button circle white' onclick='showNotes()' >
          <%= image_pack_tag 'bulb.png', alt: 'Notizen' %>
        </button>
        <button onclick="updateFlashcard()" class='button circle white'>
          <%= render partial: 'shared/icons/check' %>
        </button>
      </div>
    </div>
  </div>
</div>

<script>
  function updateFlashcard() {
    const data = getFlashcardData();
    const question = document.getElementById('question');
    const stackId = question.dataset.stackId;
    const id = question.dataset.flashcardId;

    fetch(`/stacks/${stackId}/flashcards/${id}`, {
      method: 'PATCH',
      body: JSON.stringify({ flashcard: data }),
      headers: new Headers({
        'Content-Type': 'application/json',
        'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
      })
    })
    .then((res) => res.text())
    .then((path) => {
      window.location.replace(path)
    })
  }

  function getFlashcardData() {
    const type = document.querySelector('.type').dataset.type;
    let answer = {};

    switch (type) {
      case 'OpenAnswer':
        answer = { answer: document.getElementById('answer').textContent };
        break;
      case 'MultipleChoice':
        answer = {
          option1: document.getElementById('mc-option1').textContent,
          option2: document.getElementById('mc-option2').textContent,
          option3: document.getElementById('mc-option3').textContent,
          option4: document.getElementById('mc-option4').textContent,
          option1_correct: document.getElementById('mc-option1-correct').checked,
          option2_correct: document.getElementById('mc-option2-correct').checked,
          option3_correct: document.getElementById('mc-option3-correct').checked,
          option4_correct: document.getElementById('mc-option4-correct').checked,
        }
        break;
      case 'SingleChoice':
        answer = {
          option1: document.getElementById('sc-option1').textContent,
          option2: document.getElementById('sc-option2').textContent,
          option3: document.getElementById('sc-option3').textContent,
          option4: document.getElementById('sc-option4').textContent,
          correct_option: parseInt(document.querySelector('input[name="sc-correct"]:checked').value),
        }
        break;
      case 'TrueFalse':
        answer = {
          correct: document.querySelector('input[name="true-false"]:checked').value === 'true',
        }
        break;
      default:
        break;
    }

    const questionText = question.textContent;
    const notes = document.getElementById('notes-text').textContent;

    return {
      question: questionText,
      notes: notes,
      type: type,
      ...answer
    }
  }

  function showAnswerSide() {
    const questionText = document.getElementById('question').textContent;
    const backsideQuestion = document.querySelector('p.question');
    backsideQuestion.textContent = questionText;
    flipCard();
  }

  function showNotes() {
    document.querySelector('.card-front.question').classList.add('invisible');
    document.getElementById('notes').classList.remove('invisible');
    flipCard();
  }

  function flipCard() {
    document.querySelector('.card-wrapper').classList.toggle('flipped');
  }
</script>

app/views/flashcards/endscreen.html.erb
<%= render partial: 'shared/header', locals: { title: 'Statistik', color: 'indigo' } %>
<p>In diesem Durchgang hast du folgende Fragen richtig beantwortet</p>
<%= render partial: 'shared/stats', locals: { stats: @percentages } %>

app/views/flashcards/new.html.erb
<%= render partial: 'shared/header', locals: { title: @stack.title, color: 'orange' } %>
<%= render 'shared/errors' %>
<div class='card-wrapper'>
  <div class='card-inner'>
    <div class='card card-front orange question'>
      <div>
        <div class='type-wrapper'>
          <div class='left'></div>
          <select id='type-select'>
            <option value='OpenAnswer'>Offene Frage</option>
            <option value='MultipleChoice'>Multiple Choice</option>
            <option value='SingleChoice'>Single Choice</option>
            <option value='TrueFalse'>Wahr / Falsch</option>
          </select>
          <div class='right'></div>
        </div>
        <h3 id='question' onclick="clearField('question')" contenteditable='true' data-stack-id='<%= @stack.id %>'>Frage bearbeiten</h3>
      </div>
      <div class='action-buttons'>
        <button class='button circle white' onclick="showAnswerSide()">
          <%= render partial: 'shared/icons/turn' %>
        </button>
      </div>
    </div>

    <div class='card card-front orange invisible' id='notes-card'>
      <div>
        <h3>Notizen</h3>
        <p id='notes-text' contenteditable='true' onclick="clearField('notes-text')">Notizen bearbeiten</p>
      </div>
      <button class='button circle white' onclick='flipCard()'>
        <%= render partial: 'shared/icons/back' %>
      </button>
    </div>

    <div class='card card-back orange answer' id='back'>
      <div>
        <p class='question'>Frage</p>
        <%# only for open answer %>
        <div class='answers open-answer' id='OpenAnswer'>
          <h3 id='answer' onclick="clearField('answer')" contenteditable='true'>Antwort bearbeiten</h3>
        </div>

        <%# only for multiple choice %>
        <div class='answers multiple-choice' id='MultipleChoice'>
          <div class='horizontal-input'>
            <input type='checkbox' id='mc-option1-correct' name='option1' value='1'>
            <label contenteditable='true' id='mc-option1' class='bold'>Antwort bearbeiten</label>
          </div>
          <div class='horizontal-input'>
            <input type='checkbox' id='mc-option2-correct' name='option2' value='2'>
            <label contenteditable='true' id='mc-option2' class='bold'>Antwort bearbeiten</label>
          </div>
          <div class='horizontal-input'>
            <input type='checkbox' id='mc-option3-correct' name='option3' value='3'>
            <label contenteditable='true' id='mc-option3' class='bold'>Antwort bearbeiten</label>
          </div>
          <div class='horizontal-input'>
            <input type='checkbox' id='mc-option4-correct' name='option4' value='4'>
            <label contenteditable='true' id='mc-option4' class='bold'>Antwort bearbeiten</label>
          </div>
          <div class='horizontal-input select-hint'>
            <%= render 'shared/icons/corner' %>
            <p>Richtige auswählen</p>
          </div>
        </div>

        <%# only for single choice %>
        <div class='answers single-choice' id='SingleChoice'>
          <div class='horizontal-input'>
            <input type='radio' id='option1' name='sc-correct' value='1'>
            <label contenteditable='true' id='sc-option1' class='bold'>Antwort bearbeiten</label>
          </div>
          <div class='horizontal-input'>
            <input type='radio' id='option2' name='sc-correct' value='2'>
            <label contenteditable='true' id='sc-option2' class='bold'>Antwort bearbeiten</label>
          </div>
          <div class='horizontal-input'>
            <input type='radio' id='option3' name='sc-correct' value='3'>
            <label contenteditable='true' id='sc-option3' class='bold'>Antwort bearbeiten</label>
          </div>
          <div class='horizontal-input'>
            <input type='radio' id='option4' name='sc-correct' value='4'>
            <label contenteditable='true' id='sc-option4' class='bold'>Antwort bearbeiten</label>
          </div>
          <div class='horizontal-input select-hint'>
            <%= render 'shared/icons/corner' %>
            <p>Richtiges auswählen</p>
          </div>
        </div>

        <%# only for true false %>
        <div class='answers true-false' id='TrueFalse'>
          <div class='horizontal-input'>
            <input type='radio' id='true' name='true-false' value='true'>
            <label for='true' class='bold'>Wahr</label>
          </div>
          <div class='horizontal-input'>
            <input type='radio' id='false' name='true-false' value='false'>
            <label for='false' class='bold'>Falsch</label>
          </div>
        </div>
      </div>

      <div class='action-buttons'>
        <button class='button circle white' id='notes-button-back' onclick='showNotes()'>
          <%= image_pack_tag 'bulb.png', alt: 'Notizen' %>
        </button>
        <button class='button circle white' onclick="createFlashcard()">
          <%= render partial: 'shared/icons/next' %>
        </button>
      </div>
    </div>
  </div>
</div>

<script>
  function clearField(id) {
    document.getElementById(id).textContent = '';
  }

  function createFlashcard() {
    const data = getFlashcardData();
    const question = document.getElementById('question');
    const stackId = question.dataset.stackId;

    fetch(`/stacks/${stackId}/flashcards`, {
      method: 'POST',
      body: JSON.stringify({ flashcard: data }),
      headers: new Headers({
        'Content-Type': 'application/json',
        'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
      })
    })
    .then((res) => res.text())
    .then((html) => {
      const content = new DOMParser().parseFromString(html, 'text/html').body.firstChild;
      const backside = document.getElementById('back');
      backside.innerHTML = '';
      backside.appendChild(content);
    })
  }

  function getFlashcardData() {
    const select = document.getElementById('type-select');
    const type = select.selectedOptions[0].value;
    let answer = {};

    switch (type) {
      case 'OpenAnswer':
        answer = { answer: document.getElementById('answer').textContent };
        break;
      case 'MultipleChoice':
        answer = {
          option1: document.getElementById('mc-option1').textContent,
          option2: document.getElementById('mc-option2').textContent,
          option3: document.getElementById('mc-option3').textContent,
          option4: document.getElementById('mc-option4').textContent,
          option1_correct: document.getElementById('mc-option1-correct').checked,
          option2_correct: document.getElementById('mc-option2-correct').checked,
          option3_correct: document.getElementById('mc-option3-correct').checked,
          option4_correct: document.getElementById('mc-option4-correct').checked,
        }
        break;
      case 'SingleChoice':
        answer = {
          option1: document.getElementById('sc-option1').textContent,
          option2: document.getElementById('sc-option2').textContent,
          option3: document.getElementById('sc-option3').textContent,
          option4: document.getElementById('sc-option4').textContent,
          correct_option: parseInt(document.querySelector('input[name="sc-correct"]:checked').value),
        }
        break;
      case 'TrueFalse':
        answer = {
          correct: document.querySelector('input[name="true-false"]:checked').value === 'true',
        }
        break;
      default:
        break;
    }

    const questionText = question.textContent;
    let notes = document.getElementById('notes-text').textContent;

    if (notes === 'Notizen bearbeiten') {
      notes = 'Keine Notizen vorhanden'
    }

    return {
      question: questionText,
      notes: notes,
      type: type,
      ...answer
    }
  }

  function showAnswerSide() {
    const questionText = document.getElementById('question').textContent;
    const backsideQuestion = document.querySelector('p.question');
    backsideQuestion.textContent = questionText;
    const select = document.getElementById('type-select');
    const type = select.selectedOptions[0].value;

    const answers = document.querySelectorAll('div.answers');

    Array.from(answers).forEach(answerBlock => {
      if (type !== answerBlock.id) {
        answerBlock.classList.add('invisible');
      } else {
        answerBlock.classList.remove('invisible');
      }
    });

    document.getElementById('notes-card').classList.add('invisible');
    flipCard();
  }

  function showNotes() {
    document.querySelector('.card-front.question').classList.add('invisible');
    document.getElementById('notes-card').classList.remove('invisible');
    flipCard();
  }

  function flipCard() {
    document.querySelector('.card-wrapper').classList.toggle('flipped');
  }
</script>