config/routes.rb
Rails.application.routes.draw do
  root to: 'stacks#index'
  get 'stats/index'
  get '/imprint', to: 'application#imprint'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users, only: [:show, :edit, :update, :destroy]
  get '/statistics', to: 'stats#index'

  resources :stacks, except: [:edit, :update] do
    resources :flashcards
  end

  get '/flashcards/:id/next', to: 'flashcards#next', as: :next_card
end

app/models/stack.rb
class Stack < ApplicationRecord
  belongs_to :user
  has_many :flashcards, dependent: :destroy
  validates :title, presence: true
end

app/controllers/stacks_controller.rb
class StacksController < ApplicationController
  before_action :require_login

  def index
    @stacks = current_user.stacks
  end

  def show
    @stack = Stack.find(params[:id])
    @flashcards = @stack.flashcards
  end

  def new
  end

  def create
    @stack = current_user.stacks.new(title: params[:title])

    if @stack.save
      render plain: stack_path(@stack)
    else
      render 'new', alert: 'Stapel konnte nicht erstellt werden.'
    end
  end

  def destroy
    stack = Stack.find(params[:id])
    if stack.destroy
      redirect_to stacks_path
    end
  end

  private
    def require_login
      unless current_user
        redirect_to login_path
      end
    end
end

app/views/stacks/index.html.erb
<div class="stacks-index">
  <header>
    <div>
      <%= image_pack_tag 'logo.svg', alt: 'Logo' %>
      <h1>Dycards</h1>
    </div>
    <div>
      <%= link_to new_stack_path, class: "button circle indigo" do %>
        <%= render partial: 'shared/icons/add' %>
      <% end %>
      <%= link_to stats_index_path, class: "button circle indigo" do %>
        <%= render partial: 'shared/icons/barchart' %>
      <% end %>
      <%= link_to user_path(current_user), class: "button circle indigo" do %>
        <%= render partial: 'shared/icons/user' %>
      <% end %>
      <%= link_to imprint_path, class: "button circle indigo" do %>
        <%= render partial: 'shared/icons/info' %>
      <% end %>
    </div>
  </header>

  <main>
    <% if @stacks.any? %>
      <% @stacks.each do |stack| %>
        <div class="card indigo stack">
          <h2><%= stack.title %></h2>

          <%= link_to stack, class: "edit-link" do %>
            <%= render partial: 'shared/icons/edit' %>
          <% end %>

          <h3><%= stack.flashcards.count %> <span>Karten</span></h3>

          <% if stack.flashcards.any? %>
            <%= link_to stack_flashcard_path(stack, stack.flashcards.first), class: "play-link button circle white" do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-play"><polygon points="5 3 19 12 5 21 5 3"></polygon></svg>
            <% end %>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <p class='no-stacks'>Du hast noch keine Stapel angelegt.</p>
    <% end %>
  </main>
</div>

app/views/stacks/new.html.erb
<div class='stacks-new'>
  <%= render partial: 'shared/header', locals: { title: 'Neuer Stack', color: 'orange' } %>

  <main>
    <%= render 'shared/errors' %>
    <div class='card orange stack'>
      <h3 id='new-stack-title' contenteditable='true' onclick="clearField()">Stapelnamen eingeben</h3>
      <button class='button circle white' id='create-stack-btn' onclick="createStack()">
        <%= render partial: 'shared/icons/check' %>
      </button>
    </div>
  </main>
</div>

<script>
  function clearField() {
    document.getElementById("new-stack-title").textContent = '';
  }

  function createStack() {
    const title = document.getElementById('new-stack-title').textContent;

    fetch('/stacks', {
      method: 'POST',
      body: JSON.stringify({ title }),
      headers: new Headers({
        'Content-Type': 'application/json',
        'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
      })
    })
    .then((res) => res.text())
    .then((path) => {
      window.location.replace(path);
    })
  }
</script>

app/views/stacks/show.html.erb
<header class="stack__edit--header">
  <%= render partial: 'shared/header', locals: { title: @stack.title, color: 'orange' } %>
  <div>
    <%= link_to new_stack_flashcard_path(@stack), class: "button circle indigo" do %>
      <%= render partial: 'shared/icons/add' %>
    <% end %>
    <%= form_with model: @stack, method: :delete do |f| %>
      <button class="button circle indigo position__fixed--bottom-right"> <%= render partial: 'shared/icons/trash' %> </button>
    <% end %>
  </div>
</header>

<div class="stack__edit--container">
  <% if @flashcards.any? %>
    <% @flashcards.each do |flashcard| %>
      <div class="stack__edit--card">
        <h2><%= flashcard.question %></h2>
        <div>
          <%= link_to stack_flashcard_path(@stack, flashcard), method: :delete, class: "edit-link" do %>
            <%= render partial: 'shared/icons/trash' %>
          <% end %>
          <%= link_to edit_stack_flashcard_path(@stack, flashcard), class: "edit-link" do %>
            <%= render partial: 'shared/icons/edit' %>
          <% end %>
        </div>
      </div>
    <% end %>
  <% else %>
    <p>Noch keine Fragen vorhanden.</p>
  <% end %>
</div>